Repository Jordan-Pierce/CoralNet-Toolbox, pull requests merged in 2025-08, with the labels that each got.

#263 New YOLOE Generator Implementation
  coralnet_toolbox/Annotations/QtMaskAnnotation.py
  coralnet_toolbox/MachineLearning/ExportDataset/QtBase.py
  coralnet_toolbox/MachineLearning/ImportDataset/QtBase.py
  coralnet_toolbox/MachineLearning/VideoInference/QtBase.py
  coralnet_toolbox/QtImageWindow.py
  coralnet_toolbox/QtMainWindow.py
  coralnet_toolbox/SeeAnything/QtDeployGenerator.py
  coralnet_toolbox/SeeAnything/QtDeployPredictor.py
  coralnet_toolbox/Tools/QtSeeAnythingTool.py
  coralnet_toolbox/utilities.py
  notebooks/YOLOE_updates.ipynb
Labels: enhancement

#265 Improve reorganize_labels method to clear existing layout before rear…
  coralnet_toolbox/QtLabelWindow.py
Labels: bug, enhancement

#266 TODOs
  coralnet_toolbox/QtProgressBar.py
  coralnet_toolbox/SAM/QtDeployPredictor.py
  coralnet_toolbox/SeeAnything/QtDeployGenerator.py
  coralnet_toolbox/Tools/QtSAMTool.py
Labels: enhancement

#269 Updated README Structure
  .github/workflows/diagram.yml
  README.md
  coralnet_toolbox/Explorer/QtExplorer.py
  coralnet_toolbox/Explorer/QtSettingsWidgets.py
  coralnet_toolbox/IO/QtOpenProject.py
  coralnet_toolbox/QtImageWindow.py
  coralnet_toolbox/Rasters/RasterTableModel.py
  coralnet_toolbox/SeeAnything/QtDeployGenerator.py
  coralnet_toolbox/__init__.py
  docs/index.md
  pyproject.toml
Labels: documentation

#270 0.0.74
  .github/workflows/diagram.yml
  README.md
  coralnet_toolbox/Annotations/QtMaskAnnotation.py
  coralnet_toolbox/CoralNet/QtDownload.py
  coralnet_toolbox/Explorer/QtExplorer.py
  coralnet_toolbox/Explorer/QtSettingsWidgets.py
  coralnet_toolbox/IO/QtOpenProject.py
  coralnet_toolbox/IO/QtSaveProject.py
  coralnet_toolbox/MachineLearning/ExportDataset/QtBase.py
  coralnet_toolbox/MachineLearning/ImportDataset/QtBase.py
  coralnet_toolbox/MachineLearning/VideoInference/QtBase.py
  coralnet_toolbox/QtImageWindow.py
  coralnet_toolbox/QtLabelWindow.py
  coralnet_toolbox/QtMainWindow.py
  coralnet_toolbox/QtProgressBar.py
  coralnet_toolbox/Rasters/RasterTableModel.py
  coralnet_toolbox/SAM/QtDeployPredictor.py
  coralnet_toolbox/SeeAnything/QtDeployGenerator.py
  coralnet_toolbox/SeeAnything/QtDeployPredictor.py
  coralnet_toolbox/Tools/QtSAMTool.py
  coralnet_toolbox/Tools/QtSeeAnythingTool.py
  coralnet_toolbox/__init__.py
  coralnet_toolbox/utilities.py
  docs/index.md
  notebooks/YOLOE_updates.ipynb
  pyproject.toml
Labels: enhancement

#272 TODOs: Explorer Aspect Ratio, YOLOE VPE not Recalculating
  coralnet_toolbox/Explorer/QtDataItem.py
  coralnet_toolbox/Explorer/QtExplorer.py
  coralnet_toolbox/MachineLearning/VideoInference/YOLO3D/run.py
  coralnet_toolbox/SAM/QtDeployPredictor.py
  coralnet_toolbox/SeeAnything/QtDeployGenerator.py
  coralnet_toolbox/SeeAnything/QtDeployPredictor.py
  docs/usage.md
Labels: bug, enhancement

#276 Updates for 0.0.74; see TODOs list for more info
  README.md
  coralnet_toolbox/Explorer/QtDataItem.py
  coralnet_toolbox/Explorer/QtExplorer.py
  coralnet_toolbox/MachineLearning/ImportDataset/QtBase.py
  coralnet_toolbox/MachineLearning/VideoInference/YOLO3D/run.py
  coralnet_toolbox/QtAnnotationWindow.py
  coralnet_toolbox/QtImageWindow.py
  coralnet_toolbox/Rasters/RasterTableModel.py
  coralnet_toolbox/SAM/QtDeployGenerator.py
  coralnet_toolbox/SAM/QtDeployPredictor.py
  coralnet_toolbox/SeeAnything/QtDeployGenerator.py
  coralnet_toolbox/SeeAnything/QtDeployPredictor.py
  coralnet_toolbox/Tools/QtPolygonTool.py
  coralnet_toolbox/Tools/QtRectangleTool.py
  docs/usage.md
  notebooks/YOLOE_updates.ipynb
Labels: enhancement

#273 feat: Add HuggingFace transformer models to Explorer (#259)
  coralnet_toolbox/Explorer/QtSettingsWidgets.py
Labels: enhancement

#281 Update documentation: add video demonstrations and enhance hotkeys se…
  README.md
  docs/index.md
  docs/usage.md
Labels: documentation
